# Generated by Django 5.2.5 on 2025-08-18 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MenuItem",
            new_name="Menu_Item",
        ),
    ]
