# Generated by Django 5.2.5 on 2025-08-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("table_number", models.IntegerField()),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("guests", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("reserved", "Reserved"), ("cancelled", "Cancelled")],
                        default="reserved",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
